default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: far-far-away_development

test:
  <<: *default
  database: far-far-away_test

production:
  <<: *default
  database: far-far-away_production
  username: far-far-away
  password: <%= ENV['FAR-FAR-AWAY_DATABASE_PASSWORD'] %>
