tatooine = Planet.create(name: "Tatooine", language: "Basic, Bocce, Huttese, Jawaese, Tusken", sector: "Arkanis", region: "Outer Rim Territories", description: "Tatooine is a sparsely inhabited desert planet. It has two suns, which provide striking sunsets.")
Planet.create(name: "Alderaan", language: "Basic", sector: "Alderaan", region: "Core Worlds", description: "Alderaan was destroyed in 0 BBY by the first Death Star.")
Planet.create(name: "Yavin IV", language: "Yuuzhan Vong, Massassi, Critokian, Basic", sector: "Gordian Reach", region: "Outer Rim Territories", description: "Yavin IV is one of the moons orbiting Yavin, a gas giant. During the Galactic Civil War, the Rebellion had a base on Yavin IV, which launched an attack that successfully destroyed the first Death Star.")
Planet.create(name: "Hoth", language: "Basic", sector: "Anoat", region: "Outer Rim Territories", description: "Hoth is made up entirely of snow and ice, and is surrounded by an asteroid belt. The temperature drops to well-below freezing at nightfall.")
Planet.create(name: "Dagobah", language: "Basic", sector: "Sluis", region: "Outer Rim Territories", description: "Dagobah is a harsh, humid, swampy planet, mostly covered in shallow marshland. It is also home to stifling forests, caves, and a diverse selection of flora and fauna.")
Planet.create(name: "Bespin", language: "Basic, Ugnaught", sector: "Anoat", region: "Outer Rim Territories", description: "Bespin is a gas giant, and is a major source of tibanna gas. It is home to many gas mining operations, which are the hubs of civilization on Bespin.")
endor = Planet.create(name: "Endor", language: "Ewokese, Yuzzum", sector: "Moddell", region: "Outer Rim Territories", description: "Endor is well-known for the vast amount of sentient species it supports. This is due to the unusually large number of shipwrecks Endor has experienced.")
naboo = Planet.create(name: "Naboo", language: "Basic", sector: "Chommell", region: "Mid Rim", description: "Naboo is comprised of a flooded cave network. Its surface has a vast array of different landscapes, from rolling plains and grassy hills to swampy lakes.")
coruscant = Planet.create(name: "Coruscant", language: "Basic, and thousands more", sector: "Corusca", region: "Core Worlds", description: "This ecumenopolis served as the capital for the Galactic Republic and Galactic Empire, among may others. It also served as the home of the Jedi Order and the Jedi Temple.")
kamino = Planet.create(name: "Kamino", language: "Basic, Kaminoan", sector: "Abrion", region: "Beyond the Outer Rim Territories", description: "This aquatic planet, located beyond the Rishi Maze, is well known for its cloning technology.")
geonosis = Planet.create(name: "Geonosis", language: "Geonosian hive-mind", sector: "Arkanis", region: "Outer Rim Territories", description: "Geonosis, seen from space, has remarkable rocky rings, and is orbited by 15 moons. Its surface is covered in harsh, rocky deserts. Both its rocks and sky are tinted shades of red.")
utapau = Planet.create(name: "Utapau", language: "Basic", sector: "Tarabba", region: "Outer Rim Territories", description: "Utapau is a remote planet in the Outer Rim Territories which is full of massive sinkholes.")
mustafar = Planet.create(name: "Mustafar", language: "Mustafarian", sector: "Atravis", region: "Outer Rim Territories", description: "Mustafar is an incredibly hot world, which holds many valuable minerals mined by the Techno Union. Due to the planet's surface being made up entirely of lava, all buildings are held up by gravity supports.")
kashyyyk = Planet.create(name: "Kashyyyk", language: "Shyriiwook", sector: "Mytaranor", region: "Mid Rim", description: "Kashyyyk is a jungle planet orbiting a single star. It is covered in wroshyr trees and teeming with flora and fauna.")
Planet.create(name: "Polis Massa", language: "Basic", sector: "Subterrel", region: "Outer Rim Territories", description: "Polis Massa is an asteroid field located far from any major hyperspace lanes. It was a planet once, though it was destroyed by a mysterious cataclysm.")
Planet.create(name: "Mygeeto", language: "Basic", sector: "Albarrio", region: "Outer Rim Territories", description: "Mygeeto is home to jagged crystalline mountain ranges and a very cold climate.")
Planet.create(name: "Felucia", language: "Felucianese, Gossam", sector: "Thanium", region: "Outer Rim Territories", description: "Felucia is a very colorful jungle planet. It is a key planet in the Perlemian Trade Route, and so was the site of many battles during the Clone Wars.")
Planet.create(name: "Cato Neimoidia", language: "Basic, Pak Pak", sector: "Quellor", region: "Colonies", description: "Cato Neimoidia is a colony world of the Neimoidians and was the base of operations for the Trade Federation. Much of the world is covered in a persistent fog. The cities are suspended above the planet's surface on bridges anchored between giant rock arches.")
Planet.create(name: "Saleucami", language: "Basic, Wroonian", sector: "Suolriep", region: "Outer Rim Territories", description: "Saleucami is a dim, arid world with scattered oases of plant growth. Its name means 'Oasis' in Wroonian, and it was so named because it was the only habitable planet within a system filled with dead worlds and meteors. These uninhabitable meteors frequently crossed paths with the planet's orbit and bombarded its surface creating calderas, and stirring up subterranean waters and minerals. These waters and minerals turned the calderas into life-filled pockets on the planet's surface. These craters of fertile soil were heated by geothermal vents and became the location of the earliest colonies on Saleucami. The planet became a trading post as a result. Saleucami had no indigenous sentient species, but its pleasant climate brought colonists to it")
Planet.create(name: "Stewjon", language: "Basic", sector: "placeholder", region: "placeholder", description: "placeholder")
Planet.create(name: "Eriadu", language: "Basic", sector: "Seswenna", region: "Outer Rim Territories", description: "Eriadu is one of the Outer Rim's most active trade centers. It sits on the intersection of several hyperspace routes, including the Rimma Trade Route, the Hydian Way, the Lipsec Run, and the Yankirk Route.")
# Planet.create(name: "Corellia", )
# Planet.create(name: "Rodia", )
# Planet.create(name: "Nal Hutta", )
# Planet.create(name: "Dantooine", )
# Planet.create(name: "Bestine IV", )
# Planet.create(name: "Ord Mantell", )
# Planet.create(name: "unknown")
# Planet.create(name: "Trandosha", )
# Planet.create(name: "Socorro", )
# Planet.create(name: "Mon Cala", )
# Planet.create(name: "Chandrila", )
# Planet.create(name: "Sullust", )
# Planet.create(name: "Toydaria", )
# Planet.create(name: "Malastare", )
# Planet.create(name: "Dathomir", )
# Planet.create(name: "Ryloth", )
# Planet.create(name: "Aleen Minor", )
# Planet.create(name: "Vulpter", )
# Planet.create(name: "Troiken", )
# Planet.create(name: "Tund", )
# Planet.create(name: "Haruun Kal", )
# Planet.create(name: "Cerea", )
# Planet.create(name: "Glee Anselm", )
# Planet.create(name: "Iridonia", )
# Planet.create(name: "Tholoth", )
# Planet.create(name: "Iktotch", )
# Planet.create(name: "Quermia", )
# Planet.create(name: "Dorin", )
# Planet.create(name: "Champala", )
# Planet.create(name: "Mirial", )
# Planet.create(name: "Serenno", )
# Planet.create(name: "Concord Dawn", )
# Planet.create(name: "Zolan", )
# Planet.create(name: "Ojom", )
# Planet.create(name: "Skako", )
# Planet.create(name: "Muunilinst", )
# Planet.create(name: "Shili", )
# Planet.create(name: "Kalee", )
# Planet.create(name: "Umbara", )
# Planet.create(name: "Jakku", )

Landmark.create(name: "Anchorhead Pass", planet: tatooine)
Landmark.create(name: "Beggar's Canyon", planet: tatooine)
Landmark.create(name: "Dune Sea", planet: tatooine)
Landmark.create(name: "Great Mesra Plateau", planet: tatooine)
Landmark.create(name: "Great Pit of Carkoon", planet: tatooine)
Landmark.create(name: "Jabba's Palace", planet: tatooine)
Landmark.create(name: "Jundland Chasm", planet: tatooine)
Landmark.create(name: "Jundland Wastes", planet: tatooine)
Landmark.create(name: "Lightning Forest", planet: endor)
Landmark.create(name: "Vacant Valley", planet: endor)
Landmark.create(name: "Molten Mountains", planet: endor)
Landmark.create(name: "Lake Sui", planet: endor)
Landmark.create(name: "Bright Tree Village", planet: endor)
Landmark.create(name: "Desert of Simoom", planet: endor)
Landmark.create(name: "Red Bush Grove", planet: endor)
Landmark.create(name: "Lianorm Swamp", planet: naboo)
Landmark.create(name: "Lake Paonga", planet: naboo)
Landmark.create(name: "Great Grass Plains", planet: naboo)
Landmark.create(name: "Gallo Mountains", planet: naboo)
Landmark.create(name: "Solleu River", planet: naboo)
Landmark.create(name: "Caves of Eleuabad", planet: naboo)
Landmark.create(name: "Lake Country", planet: naboo)
Landmark.create(name: "Sacred Forest of Naboo", planet: naboo)
Landmark.create(name: "Theed Royal Palace", planet: naboo)
Landmark.create(name: "Lors", planet: naboo)
Landmark.create(name: "Lasay Swamp", planet: naboo)
Landmark.create(name: "Galactic Museum", planet: coruscant)
Landmark.create(name: "Great Western Sea", planet: coruscant)
Landmark.create(name: "Imperial Palace", planet: coruscant)
Landmark.create(name: "Jedi Temple", planet: coruscant)
Landmark.create(name: "Manarai Mountains", planet: coruscant)
Landmark.create(name: "Senate Building", planet: coruscant)
Landmark.create(name: "University of Coruscant", planet: coruscant)
Landmark.create(name: "Tipoca City", planet: kamino)
Landmark.create(name: "Baran Wu", planet: kamino)
Landmark.create(name: "Su Des", planet: kamino)
Landmark.create(name: "Slici Canyon", planet: kamino)
Landmark.create(name: "Tal An Fissures", planet: kamino)
Landmark.create(name: "Glascretia", planet: kamino)
Landmark.create(name: "Razoral Reefs", planet: kamino)
Landmark.create(name: "Badlands of N'g'zi", planet: geonosis)
Landmark.create(name: "Im'g'twe Hills", planet: geonosis)
Landmark.create(name: "Petranaki Arena", planet: geonosis)
Landmark.create(name: "Progate Temple", planet: geonosis)
Landmark.create(name: "Ebon Sea", planet: geonosis)
Landmark.create(name: "Golbah's Pit", planet: geonosis)
Landmark.create(name: "Caltrop Field", planet: geonosis)
Landmark.create(name: "E'Y-Akh Desert", planet: geonosis)
Landmark.create(name: "N'ge'u Valley", planet: geonosis)
Landmark.create(name: "Pau City", planet: utapau)
Landmark.create(name: "Grottoes of Coranth", planet: utapau)
Landmark.create(name: "Promenade of Seven Guilds", planet: utapau)
Landmark.create(name: "Pahum Cultural Center", planet: utapau)
Landmark.create(name: "Black Sun Fortress", planet: mustafar)
Landmark.create(name: "Mensix Mining Facility", planet: mustafar)
Landmark.create(name: "Klegger Corp Mining Facility", planet: mustafar)
Landmark.create(name: "Berken's Flow", planet: mustafar)
Landmark.create(name: "Tulrus Island", planet: mustafar)
Landmark.create(name: "Burning Plains", planet: mustafar)
Landmark.create(name: "Smoking Forest", planet: mustafar)
Landmark.create(name: "Crystal Flats", planet: mustafar)
Landmark.create(name: "Gizor Dellso's Droid Foundry", planet: mustafar)
Landmark.create(name: "Jedi Enclave", planet: mustafar)
Landmark.create(name: "Kachirho", planet: kashyyyk)
Landmark.create(name: "Kkowir Forest", planet: kashyyyk)
Landmark.create(name: "Myyydril Caverns", planet: kashyyyk)
Landmark.create(name: "Shadowlands", planet: kashyyyk)
Landmark.create(name: "Wawaatt Archipelago", planet: kashyyyk)
Landmark.create(name: "Wartaki Islands", planet: kashyyyk)

Event.create(name: "Podracing", planet: tatooine)
Event.create(name: "Bullseye womp rats", planet: tatooine)
