Planet.create(name: "Tatooine", language: "Basic, Bocce, Huttese, Jawaese, Tusken", sector: "Arkanis", region: "Outer Rim Territories", description: "Tatooine is a sparsely inhabited desert planet. It has two suns, which provide striking sunsets.")
Planet.create(name: "Alderaan", language: "Basic", sector: "Alderaan", region: "Core Worlds", description: "placeholder")
Planet.create(name: "Yavin IV", language: "Yuuzhan Vong, Massassi, Critokian, Basic", sector: "Gordian Reach", region: "Outer Rim Territories", description: "placeholder")
Planet.create(name: "Hoth", language: "Basic", sector: "Anoat", region: "Outer Rim Territories", description: "placeholder")
Planet.create(name: "Dagobah", language: "Basic", sector: "Sluis", region: "Outer Rim Territories", description: "placeholder")
Planet.create(name: "Bespin", language: "Basic, Ugnaught", sector: "Anoat", region: "Outer Rim Territories", description: "placeholder")
Planet.create(name: "Endor", language: "Ewokese, Yuzzum", sector: "Moddell", region: "Outer Rim Territories", description: "placeholder")
Planet.create(name: "Naboo", language: "Basic", sector: "Chommell", region: "Mid Rim", description: "placeholder")
Planet.create(name: "Coruscant", language: "Basic, and thousands more", sector: "Corusca", region: "Core Worlds", description: "placeholder")
Planet.create(name: "Kamino", language: "Basic, Kaminoan", sector: "Abrion", region: "Beyond the Outer Rim Territories", description: "placeholder")
Planet.create(name: "Geonosis", language: "Geonosian hive-mind", sector: "Arkanis", region: "Outer Rim Territories", description: "placeholder")
Planet.create(name: "Utapau", language: "Basic", sector: "Tarabba", region: "Outer Rim Territories", description: "Utapau is a remote planet in the Outer Rim Territories which is full of massive sinkholes.")
Planet.create(name: "Mustafar", language: "Mustafarian", sector: "Atravis", region: "Outer Rim Territories", description: "Mustafar is an incredibly hot world, which holds many valuable minerals mined by the Techno Union. Due to the planet's surface being made up entirely of lava, all buildings are held up by gravity supports.")
Planet.create(name: "Kashyyyk", language: "Shyriiwook", sector: "Mytaranor", region: "Mid Rim", description: "Kashyyyk is a jungle planet orbiting a single star. It is covered in wroshyr trees and teeming with flora and fauna.")
Planet.create(name: "Polis Massa", language: "Basic", sector: "Subterrel", region: "Outer Rim Territories", description: "Polis Massa is an asteroid field located far from any major hyperspace lanes. It was a planet once, though it was destroyed by a mysterious cataclysm.")
Planet.create(name: "Mygeeto", language: "Basic", sector: "Albarrio", region: "Outer Rim Territories", description: "Mygeeto is home to jagged crystalline mountain ranges and a very cold climate.")
Planet.create(name: "Felucia", language: "Felucianese, Gossam", sector: "Thanium", region: "Outer Rim Territories", description: "Felucia is a very colorful jungle planet. It is a key planet in the Perlemian Trade Route, and so was the site of many battles during the Clone Wars.")
Planet.create(name: "Cato Neimoidia", language: "Basic, Pak Pak", sector: "Quellor", region: "Colonies", description: "Cato Neimoidia is a colony world of the Neimoidians and was the base of operations for the Trade Federation. Much of the world is covered in a persistent fog. The cities are suspended above the planet's surface on bridges anchored between giant rock arches.")
Planet.create(name: "Saleucami", language: "Basic, Wroonian", sector: "Suolriep", region: "Outer Rim Territories", description: "Saleucami is a dim, arid world with scattered oases of plant growth. Its name means 'Oasis' in Wroonian, and it was so named because it was the only habitable planet within a system filled with dead worlds and meteors. These uninhabitable meteors frequently crossed paths with the planet's orbit and bombarded its surface creating calderas, and stirring up subterranean waters and minerals. These waters and minerals turned the calderas into life-filled pockets on the planet's surface. These craters of fertile soil were heated by geothermal vents and became the location of the earliest colonies on Saleucami. The planet became a trading post as a result. Saleucami had no indigenous sentient species, but its pleasant climate brought colonists to it")
Planet.create(name: "Stewjon", language: "Basic", sector: "placeholder", region: "placeholder", description: "placeholder")
Planet.create(name: "Eriadu", language: "Basic", sector: "Seswenna", region: "Outer Rim Territories", description: "Eriadu is one of the Outer Rim's most active trade centers. It sits on the intersection of several hyperspace routes, including the Rimma Trade Route, the Hydian Way, the Lipsec Run, and the Yankirk Route.")
# Planet.create(name: "Corellia", )
# Planet.create(name: "Rodia", )
# Planet.create(name: "Nal Hutta", )
# Planet.create(name: "Dantooine", )
# Planet.create(name: "Bestine IV", )
# Planet.create(name: "Ord Mantell", )
# Planet.create(name: "unknown")
# Planet.create(name: "Trandosha", )
# Planet.create(name: "Socorro", )
# Planet.create(name: "Mon Cala", )
# Planet.create(name: "Chandrila", )
# Planet.create(name: "Sullust", )
# Planet.create(name: "Toydaria", )
# Planet.create(name: "Malastare", )
# Planet.create(name: "Dathomir", )
# Planet.create(name: "Ryloth", )
# Planet.create(name: "Aleen Minor", )
# Planet.create(name: "Vulpter", )
# Planet.create(name: "Troiken", )
# Planet.create(name: "Tund", )
# Planet.create(name: "Haruun Kal", )
# Planet.create(name: "Cerea", )
# Planet.create(name: "Glee Anselm", )
# Planet.create(name: "Iridonia", )
# Planet.create(name: "Tholoth", )
# Planet.create(name: "Iktotch", )
# Planet.create(name: "Quermia", )
# Planet.create(name: "Dorin", )
# Planet.create(name: "Champala", )
# Planet.create(name: "Mirial", )
# Planet.create(name: "Serenno", )
# Planet.create(name: "Concord Dawn", )
# Planet.create(name: "Zolan", )
# Planet.create(name: "Ojom", )
# Planet.create(name: "Skako", )
# Planet.create(name: "Muunilinst", )
# Planet.create(name: "Shili", )
# Planet.create(name: "Kalee", )
# Planet.create(name: "Umbara", )
# Planet.create(name: "Jakku", )
